### ISSUE TITLE
How can I add a new category to the list of existing categories

### ISSUE THREAD

**Issue by odebroqueville** [abenzer/represent-map#75]
I'd like to add the category "3D printing workshops".

Would somebody please explain how I can do this.

Thank you.

**Comment by tg040** [comment]
I did this recently. It`s messy but it is easy. 

1. You need to edit the index.php file and add the category to the array on both instances and in the select element as well. 
2. Then you need to add that category to the admin/edit.php which uses the select element. 
3. Then you need to create an image with the name of the category value and place it in the images dir.

Hopefully, I'll make some time to commit a new version to facilitate this process.

**Comment by odebroqueville** [comment]
That worked nicely, thank you.
I just increased the menu width slightly in the map.css file to accommodate the longer category title.
