### ISSUE TITLE
Map display and Startups label have disappeared

### ISSUE THREAD

**Issue by odebroqueville** [abenzer/represent-map#80]
I added data to the MySQL database using phpMyAdmin and changed the structure of the places table to allow for certain NULL values.
Now, the Startups label no longer appears in the right sidebar and the map doesn't get displayed.
Please see here: www.geneva-startups.ch
Is there a limited number of startups one can add? (I added 1'315 startups)

**Comment by odebroqueville** [comment]
Alex, Tara, Sean, please don't let us down... I really need help with this... I spent lots of time to create and share a map of startups from Geneva and Switzerland.
PLEASE HELP!!!

**Comment by odebroqueville** [comment]
It appears that the problem had to do with encoding. I changed lines 185 to 188 of index.php as follows:

              $place[title] = utf8_encode(htmlspecialchars_decode(addslashes(htmlspecialchars($place[title]))),ENT_COMPAT,'UTF-8', false);
              $place[description] = utf8_encode(str_replace(array("\n", "\t", "\r"), "", htmlspecialchars_decode(addslashes(htmlspecialchars($place[description])))),ENT_COMPAT,'UTF-8', false);
              $place[uri] = utf8_encode(addslashes(htmlspecialchars($place[uri])),ENT_COMPAT,'UTF-8', false);
              $place[address] = utf8_encode(htmlspecialchars_decode(addslashes(htmlspecialchars($place[address]))),ENT_COMPAT,'UTF-8', false);

This solved the problem.

**Comment by abenzer** [comment]
Cool, thanks for the update. Glad you worked it out.

**Comment by odebroqueville** [comment]
Actually, the problem is half solved! I've got the markers and the map displayed now, but the labels and infowindows are empty!

**Comment by abenzer** [comment]
Do you see any JS errors in your console when loading the page?

**Comment by odebroqueville** [comment]
Nope! I just see the following:
Google Maps API warning: SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages
which refers to util.js line 32.
I think the problem still has to do with the encoding somehow!

**Comment by odebroqueville** [comment]
Alex, Would you please tell me what you are trying to do with this code:
htmlspecialchars_decode(addslashes(htmlspecialchars($place[title])))
It doesn't appear to be working for French and German. I'm really struggling to find an alternative with a wider scope in terms of compatible languages.

**Comment by odebroqueville** [comment]
I tried changing the charset to ISO-8859-1. The web page source looks fine, but it just won't render on the map.

**Comment by odebroqueville** [comment]
Finally working! Good God, that was a tough one to crack! Here's the code that I changed:
              $place[title] = htmlentities($place[title],ENT_QUOTES,"ISO-8859-1");
              $place[description] = htmlentities(str_replace(array("\n", "\t", "\r"), "", $place[description]),ENT_QUOTES,"ISO-8859-1");
              $place[uri] = htmlentities($place[uri],ENT_QUOTES,"ISO-8859-1");
              $place[address] = htmlentities(str_replace(array("\n", "\t", "\r"), "", $place[address]),ENT_QUOTES,"ISO-8859-1");
